/**
 * AUTO-GENERATED by WebSpec (do not edit by hand)
 * ROUTES_JSON: {{ROUTES_JSON}}
 */
import React from "react";
import { createBrowserRouter, RouterProvider } from "react-router-dom";

type RouteDef = { path: string; page: string };

const ROUTES: RouteDef[] = JSON.parse(`{{ROUTES_JSON}}`);

function lazyPage(page: string) {
  return React.lazy(() => import(`./pages/${page}.tsx`));
}

export function AppRouter() {
  const router = createBrowserRouter(
    ROUTES.map((r) => ({
      path: r.path,
      element: (
        <React.Suspense fallback={<div style={{ padding: 16 }}>Loading…</div>}>
          {React.createElement(lazyPage(r.page))}
        </React.Suspense>
      )
    }))
  );
  return <RouterProvider router={router} />;
}
